/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { Public } from "../../decorators/public.decorator";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateEntitytestArgs } from "./CreateEntitytestArgs";
import { UpdateEntitytestArgs } from "./UpdateEntitytestArgs";
import { DeleteEntitytestArgs } from "./DeleteEntitytestArgs";
import { EntitytestCountArgs } from "./EntitytestCountArgs";
import { EntitytestFindManyArgs } from "./EntitytestFindManyArgs";
import { EntitytestFindUniqueArgs } from "./EntitytestFindUniqueArgs";
import { Entitytest } from "./Entitytest";
import { EntitytestService } from "../entitytest.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Entitytest)
export class EntitytestResolverBase {
  constructor(
    protected readonly service: EntitytestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @Public()
  @graphql.Query(() => MetaQueryPayload)
  async _entitytestsMeta(
    @graphql.Args() args: EntitytestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @Public()
  @graphql.Query(() => [Entitytest])
  async entitytests(
    @graphql.Args() args: EntitytestFindManyArgs
  ): Promise<Entitytest[]> {
    return this.service.findMany(args);
  }

  @Public()
  @graphql.Query(() => Entitytest, { nullable: true })
  async entitytest(
    @graphql.Args() args: EntitytestFindUniqueArgs
  ): Promise<Entitytest | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Entitytest)
  @nestAccessControl.UseRoles({
    resource: "Entitytest",
    action: "create",
    possession: "any",
  })
  async createEntitytest(
    @graphql.Args() args: CreateEntitytestArgs
  ): Promise<Entitytest> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Entitytest)
  @nestAccessControl.UseRoles({
    resource: "Entitytest",
    action: "update",
    possession: "any",
  })
  async updateEntitytest(
    @graphql.Args() args: UpdateEntitytestArgs
  ): Promise<Entitytest | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Entitytest)
  @nestAccessControl.UseRoles({
    resource: "Entitytest",
    action: "delete",
    possession: "any",
  })
  async deleteEntitytest(
    @graphql.Args() args: DeleteEntitytestArgs
  ): Promise<Entitytest | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
